import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "@/providers";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className="max-w-screen overflow-x-hidden">
          <div className="grid grid-rows-[auto_1fr_auto] min-h-screen text-foreground bg-background">
            <Header />
            <main>{children}</main>
            <Footer />
          </div>
          <Toaster />
        </body>
      </Providers>
    </html>
  );
}
